name: PR Check
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: actions/checkout@v3
      - name: Check formatting
        run: deno fmt --check
      - name: Lint
        run: deno lint
